---
name: Pull request labeler
# on:
#   schedule:
#     - cron: "*/5 * * * *"

on:
  # (optional) Run workflow manually
  workflow_dispatch:
  
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: paulfantom/periodic-labeler@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LABEL_MAPPINGS_FILE: .github/labeler.yml
